#!/bin/bash
# Auto-generated by Tequila — self-cleans on exit
trap 'rm -f "$0"' EXIT
cd "${WINEPREFIX:-$(dirname "$(realpath "$0")")}" || exit 1

# Environment — populated by Tequila at runtime
__TEQUILA_EXPORTS__

export PS1='__TEQUILA_PS1__ $PS1'
cd '__TEQUILA_PREFIX_PATH__'

echo "=== Tequila prefix '__TEQUILA_PREFIX_NAME__' ==="
echo "Environment Vars loaded:"
__TEQUILA_BANNER__
exec "$SHELL" -i
